[agent]
  interval = "10s"
  flush_interval = "10s"
  omit_hostname = true

# Entrada
[[inputs.mqtt_consumer]]
  servers = ["tcp://${MQTT_HOST}:${MQTT_PORT}"]
  topics  = ["${MQTT_TOPIC}"]
  client_id = "${MQTT_CLIENT_ID}"
  qos = 0

  data_format = "json"
  name_override = "dht11"
  tag_keys = ["client_id"]

# Saida
[[outputs.influxdb_v2]]
  urls = ["${INFLUX_URL}"]
  token = "${INFLUX_TOKEN}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET}"
